---
# Copyright 2023 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
- name: Gather user fact
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - "user"
  when:
    - ansible_user is undefined

- name: Ensure new config directory exists
  tags:
    - update
    - neutron_dhcp
  become: true
  ansible.builtin.file:
    path: "{{ edpm_neutron_dhcp_agent_config_dir }}"
    state: directory
    setype: "container_file_t"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: "0755"

- name: Check if old config directory exists
  tags:
    - update
    - neutron_dhcp
  ansible.builtin.stat:
    path: "/var/lib/config-data/ansible-generated/neutron-dhcp-agent"
  register: edpm_neutron_dhcp_old_config_dir

- name: Move config files from old location to new location
  tags:
    - update
    - neutron_dhcp
  become: true
  when:
    - edpm_neutron_dhcp_old_config_dir.stat.exists
    - edpm_neutron_dhcp_old_config_dir.stat.isdir
  block:
    - name: Find config files in old location
      ansible.builtin.find:
        paths: "/var/lib/config-data/ansible-generated/neutron-dhcp-agent"
        file_type: file
        recurse: false
      register: edpm_neutron_dhcp_old_config_files

    - name: Copy config files to new location
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ edpm_neutron_dhcp_agent_config_dir }}/{{ item.path | basename }}"
        remote_src: true
        setype: "container_file_t"
        owner: "{{ ansible_user | default(ansible_user_id) }}"
        group: "{{ ansible_user | default(ansible_user_id) }}"
        mode: "0644"
      loop: "{{ edpm_neutron_dhcp_old_config_files.files }}"
      when:
        - edpm_neutron_dhcp_old_config_files.files is defined
        - edpm_neutron_dhcp_old_config_files.files | length > 0

    - name: Remove old config directory
      ansible.builtin.file:
        path: "/var/lib/config-data/ansible-generated/neutron-dhcp-agent"
        state: absent
