---

- name: Download packages for edpm_bootstrap role
  when: '"bootstrap" in edpm_download_cache_running_services'
  ansible.builtin.include_role:
    name: osp.edpm.edpm_bootstrap
    tasks_from: download_cache.yml
  tags:
    - edpm_bootstrap
    - download_cache

- name: Download packages for edpm_podman role
  when: ("install-os" in edpm_download_cache_running_services) or
        ("configure-os" in edpm_download_cache_running_services) or
        ("run-os" in edpm_download_cache_running_services)
  ansible.builtin.include_role:
    name: osp.edpm.edpm_podman
    tasks_from: download_cache.yml
  tags:
    - edpm_podman
    - download_cache

- name: Download packages for edpm_tuned role
  when: '"bootstrap" in edpm_download_cache_running_services'
  ansible.builtin.include_role:
    name: osp.edpm.edpm_tuned
    tasks_from: download_cache.yml
  tags:
    - edpm_tuned
    - download_cache

- name: Download packages for edpm_kernel role
  when: '"bootstrap" in edpm_download_cache_running_services'
  ansible.builtin.include_role:
    name: osp.edpm.edpm_kernel
    tasks_from: download_cache.yml
  tags:
    - edpm_kernel
    - download_cache

- name: Download packages for edpm_network_config role
  when: '"configure-network" in edpm_download_cache_running_services'
  ansible.builtin.include_role:
    name: osp.edpm.edpm_network_config
    tasks_from: download_cache.yml
  tags:
    - edpm_network_config
    - download_cache

- name: Download packages for edpm_sshd role
  when: ("install-os" in edpm_download_cache_running_services) or
        ("configure-os" in edpm_download_cache_running_services) or
        ("run-os" in edpm_download_cache_running_services)
  ansible.builtin.include_role:
    name: osp.edpm.edpm_sshd
    tasks_from: download_cache.yml
  tags:
    - edpm_sshd
    - download_cache

- name: Download packages for edpm_libvirt role
  when: '"libvirt" in edpm_download_cache_running_services'
  ansible.builtin.include_role:
    name: osp.edpm.edpm_libvirt
    tasks_from: download_cache.yml
  tags:
    - edpm_libvirt
    - download_cache

- name: Download packages for edpm_iscsid role
  # iscsid is part of the "nova" EDPM service
  when: '"nova" in edpm_download_cache_running_services'
  ansible.builtin.include_role:
    name: osp.edpm.edpm_iscsid
    tasks_from: download_cache.yml
  tags:
    - edpm_iscsid
    - download_cache

- name: Download packages for edpm_accel_drivers role
  when: '"accel_drivers" in edpm_download_cache_running_services'
  ansible.builtin.include_role:
    name: osp.edpm.edpm_accel_drivers
    tasks_from: download_cache.yml
  tags:
    - edpm_accel_drivers
    - download_cache

- name: Download packages for edpm_multipathd role
  # multipathd is part of the "nova" EDPM service
  when: '"nova" in edpm_download_cache_running_services'
  ansible.builtin.include_role:
    name: osp.edpm.edpm_multipathd
    tasks_from: download_cache.yml
  tags:
    - edpm_multipathd
    - download_cache
