---
# Copyright 2024 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# "edpm_update" will search for and load any operating system variable file

- name: Gather ansible_local facts
  ansible.builtin.setup:
    filter: ansible_local
  when:
    - ansible_local is not defined

- name: Apply kernel patch via kpatch
  ansible.builtin.include_tasks: kpatch.yml
  when:
    - edpm_update_enable_kpatch
    - not ansible_local.bootc

- name: Update packages
  ansible.builtin.include_tasks: packages.yml
  when:
    - edpm_update_enable_packages_update
    - not ansible_local.bootc

- name: Update OS (bootc)
  ansible.builtin.include_tasks: bootc.yml
  when: ansible_local.bootc

- name: Update containers
  ansible.builtin.include_tasks: containers.yml
  when:
    - edpm_update_enable_containers_update
