---

- name: Import edpm_ovs role for independent openvswitch update
  ansible.builtin.import_role:
    name: osp.edpm.edpm_ovs
    tasks_from: update
  tags:
    - edpm_update

- name: Ensure openvswitch is excluded from bulk update
  ansible.builtin.set_fact:
    _exclude_packages: >-
      {{
        _exclude_packages | default([]) +
        edpm_update_exclude_packages | default([]) +
        ['openvswitch'] |
        ansible.builtin.unique
      }}
  tags:
    - edpm_update

- name: Apply packages updates
  become: true
  ansible.builtin.dnf:  # noqa: package-latest
    name: "*"
    state: latest
    update_cache: true
    exclude: "{{ _exclude_packages }}"
  tags:
    - edpm_update
