---

argument_specs:
  # ./roles/edpm_ovn_bgp_agent/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_ovn_bgp_agent role.
    options:
      edpm_ovn_bgp_agent_enable:
        type: bool
        default: true
        description: Enable the bgp agent or not?
      edpm_ovn_bgp_agent_debug:
        type: bool
        default: true
        description: Start the agent in a debug mode?
      edpm_ovn_bgp_agent_reconcile_interval:
        description: Reconciliation interval in seconds
        type: int
        default: 300
      edpm_ovn_bgp_agent_expose_tenant_networks:
        description: Exposing tenant networks.
        type: bool
        default: false
      edpm_ovn_bgp_agent_expose_ipv6_gua_tenant_networks:
        description: Exposing tenant networks with IPv6 addresses.
        type: bool
        default: false
      edpm_ovn_bgp_agent_driver:
        type: str
        default: nb_ovn_bgp_driver
      edpm_ovn_bgp_agent_private_key:
        description: Location of private TLS key. Keep it safe.
        type: path
        default: /etc/pki/tls/private/ovn_bgp_agent.key
      edpm_ovn_bgp_agent_certificate:
        description: Location of TLS certificate used by BGP agent.
        type: path
        default: /etc/pki/tls/certs/ovn_bgp_agent.crt
      edpm_ovn_bgp_agent_ca_cert:
        description: Location of IPA certificate.
        type: path
        default: /etc/ipa/ca.crt
      edpm_ovn_bgp_agent_internal_tls_enable:
        description: Enable internal TLS.
        type: bool
        default: false
      edpm_ovn_bgp_agent_config_basedir:
        description: Location of BGP agent configuration base directory.
        type: path
        default: "/var/lib/openstack/ovn-bgp-agent"
      edpm_ovn_bgp_agent_bgp_as:
        description: BGP Autonomous System number
        type: int
        default: 64999
      edpm_ovn_bgp_agent_clear_vrf_routes_on_startup:
        type: bool
        default: false
        description: Clear VRF routes on startup.
      edpm_ovn_bgp_agent_bgp_nic:
        type: str
        default: bgp-nic
        description: The name of the interface used within the VRF to expose the IPs and/or Networks.
      edpm_ovn_bgp_agent_bgp_vrf:
        type: str
        default: bgp-vrf
        description: The name of the VRF to be used to expose the IPs and/or Networks through BGP.
      edpm_ovn_bgp_agent_bgp_vrf_table_id:
        description: The Routing Table ID that the VRF should use. If it does not exist, this table will be created.
        type: int
        default: 10
      edpm_ovn_bgp_agent_root_helper:
        description: Root helper for BGP agent.
        type: str
        default: "sudo ovn-bgp-agent-rootwrap /etc/ovn-bgp-agent/rootwrap.conf"
      edpm_ovn_bgp_agent_root_helper_daemon:
        description: Root helper for BGP agent as a daemon.
        type: str
        default: "sudo ovn-bgp-agent-rootwrap-daemon /etc/ovn-bgp-agent/rootwrap.conf"
      edpm_ovn_bgp_agent_ovsdb_connection:
        description: Connection to the OVS database, including port and protocol.
        type: str
        default: "tcp:127.0.0.1:6640"
      edpm_ovn_bgp_agent_ovs_manager:
        type: str
        default: "ptcp:6640:127.0.0.1"
        description: OVSDB connection method.
      edpm_ovn_bgp_agent_image:
        type: str
        default: "quay.io/podified-antelope-centos9/openstack-ovn-bgp-agent:current-podified"
        description: OVN BGP agent image.
      edpm_ovn_bgp_agent_images_download_delay:
        type: int
        default: 5
        description: The seconds between retries for failed download tasks
      edpm_ovn_bgp_agent_images_download_retries:
        type: int
        default: 5
        description: The number of retries for failed download tasks
      edpm_ovn_bgp_agent_address_scopes:
        description: |
          Allows to filter on the address scope.
          Only networks with the same address scope on the provider and internal interface are announced.
        type: str
        default: ''
      edpm_ovn_bgp_agent_bgp_router_id:
        description: |
          Router ID to be used by the Agent when running in BGP mode and configuring the VRF route leaking.
        type: str
        default: ''
      edpm_ovn_bgp_agent_evpn_local_ip:
        description: |
          IP address of local EVPN VXLAN (tunnel) endpoint. This option can be used instead of the edpm_ovn_bgp_agent_evpn_nic.
          If none specified, it will take the one from the loopback device.
        type: str
        default: ''
      edpm_ovn_bgp_agent_evpn_nic:
        description: |
          NIC with the IP address to use for the local EVPN VXLAN (tunnel) endpoint.
          This option can be used instead of the edpm_ovn_bgp_agent_evpn_local_ip.
          If none specified, it will take the one from the loopback device.
        type: str
        default: ''
      edpm_ovn_bgp_agent_evpn_udp_dstport:
        default: ''
        type: str
        description: The UDP port used for EVPN VXLAN communication. Originally set to '4789'

      edpm_ovn_bgp_agent_common_volumes:
        type: list
        description: List of mounted volumes with optional permissions.
        default:
          - /etc/hosts:/etc/hosts:ro
          - /etc/localtime:/etc/localtime:ro
          - /dev/log:/dev/log
          - /etc/iproute2:/etc/iproute2
          - /var/lib/kolla/config_files/ovn_bgp_agent.json:/var/lib/kolla/config_files/config.json:ro
          - /var/lib/openstack/ovn-bgp-agent:/var/lib/kolla/config_files/src:ro
          - /run/frr:/run/frr:shared,z
          - /run/openvswitch:/run/openvswitch:shared,z

      edpm_ovn_bgp_agent_tls_volumes:
        type: list
        description: list of mounted TLS certificate volumes
        default:
          - "/var/lib/openstack/certs/ovn-bgp-agent/default/ca.crt:/etc/pki/tls/certs/ovndbca.crt:ro,z"
          - "/var/lib/openstack/certs/ovn-bgp-agent/default/tls.crt:/etc/pki/tls/certs/ovndb.crt:ro,z"
          - "/var/lib/openstack/certs/ovn-bgp-agent/default/tls.key:/etc/pki/tls/private/ovndb.key:ro,Z"
