---
- name: Prepare test_deps
  hosts: all
  gather_facts: false
  roles:
    - role: ../../../../molecule/common/test_deps
      test_deps_extra_packages:
        - podman
        - curl
- name: Prepare
  hosts: all
  gather_facts: false
  roles:
    - role: osp.edpm.env_data
  vars_files:
    - ../../defaults/main.yml
