---

- name: Download needed container image
  containers.podman.podman_image:
    name: "{{ edpm_nova_compute_image }}"
  become: true
  register: edpm_nova_image_download
  until: edpm_nova_image_download.failed == failed
  retries: "{{ edpm_nova_image_download_retries }}"
  delay: "{{ edpm_nova_image_download_delay }}"
