---
# Copyright 2023 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Configure OVN BGP agent
  ansible.builtin.template:
    src: ovn-bgp-agent.conf.j2
    dest: "{{ edpm_ovn_bgp_agent_config_basedir }}/etc/ovn-bgp-agent/bgp-agent.conf"
    mode: "644"
    selevel: s0
    setype: container_file_t
  register: _ovn_bgp_agent_config_result

- name: Discover secrets in {{ edpm_ovn_bgp_agent_config_src }}
  ansible.builtin.find:
    paths: "{{ edpm_ovn_bgp_agent_config_src }}"
    file_type: file
    recurse: true
    patterns:
      - "*ovn-bgp-agent*conf"
  register: edpm_ovn_bgp_agent_secrets
  delegate_to: localhost
  become: false

- name: Flatten secrets into {{ edpm_ovn_bgp_agent_config_basedir }}
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ edpm_ovn_bgp_agent_config_basedir }}/etc/ovn-bgp-agent/{{ item.path | basename }}"
    setype: "container_file_t"
    mode: "0644"
  loop: "{{ edpm_ovn_bgp_agent_secrets.files }}"

- name: Add OVS Manager
  block:
    - name: Check if OVS Manager already exists
      ansible.builtin.shell: |
        set -o pipefail
        ovs-vsctl show | grep -q "Manager"
      register: ovs_manager_configured
      failed_when: false
      changed_when: true
    - name: Add OVS Manager if not exists
      ansible.builtin.shell: >
        ovs-vsctl --timeout=5 --id=@manager -- create Manager target=\"{{ edpm_ovn_bgp_agent_ovs_manager }}\" -- add Open_vSwitch . manager_options @manager
      when: ovs_manager_configured.rc == 1
      register: ovs_manager_if_not_exists
      changed_when: ovs_manager_if_not_exists.rc == 0
      failed_when: ovs_manager_if_not_exists.rc != 0
