---
# Copyright 2023 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Include host prep tasks for ovn_cluster
  ansible.builtin.import_tasks: install_ovn.yml
  when: edpm_ovn_bgp_agent_local_ovn_routing

- name: Include host prep tasks
  ansible.builtin.import_tasks: install.yml

- name: Configure in node ovn cluster for ovn_bgp_agent
  ansible.builtin.import_tasks: configure_ovn.yml
  when: edpm_ovn_bgp_agent_local_ovn_routing

- name: Configure ovn_bgp_agent
  ansible.builtin.import_tasks: configure.yml

- name: Ensure in node ovn cluster for ovn_bgp_agent is running
  ansible.builtin.import_tasks: run_ovn.yml
  when: edpm_ovn_bgp_agent_local_ovn_routing

- name: Ensure ovn_bgp_agent is running
  ansible.builtin.import_tasks: run.yml
