---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  provision: no
  parallel: true
  default_box: 'generic/centos9s'
platforms:
- name: edpm-cleanup
  memory: 2048
  cpus: 2
  provider_options:
    cpu_mode: 'host-passthrough'
    nested: true
    machine_type: 'q35'
    storage_pool_name: 'default'
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
    prepare: ../default/prepare.yml
    verify: ../default/verify.yml
verifier:
  name: ansible
scenario:
  # The vagrant scenario is for development/debug.
  # Disable all tests so they don't run in CI
  test_sequence: []
  # test_sequence:
  #   - destroy
  #   - create
  #   - prepare
  #   - converge
  #   - verify
