---
- name: Verify ovn_bgp_agent
  gather_facts: false
  hosts: compute-1
  vars:
    test_helper_dir: "../../../../molecule/test-helpers"
  tasks:
    - name: ensure expected directories exist
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_dir.yaml"
      loop:
        - "/var/lib/openstack/ovn-bgp-agent/etc/ovn-bgp-agent/bgp-agent.conf"
        - "/var/lib/edpm-config/container-startup-config/ovn_bgp_agent"

    - name: ensure podman container exists and are running
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_podman.yaml"
      loop:
        - "ovn_bgp_agent"

    - name: ensure systemd services are defined and functional
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_systemd_unit.yaml"
      loop:
        - {"name": "edpm_ovn_bgp_agent.service"}

    - name: ensure kolla_set_configs copied the expected files
      become: true
      ansible.builtin.shell: |
        podman logs ovn_bgp_agent 2>&1 | grep "{{item}}" > /dev/null
      loop:
        - "Copying /var/lib/kolla/config_files/src/etc/ovn-bgp-agent/bgp-agent.conf to /etc/ovn-bgp-agent/bgp-agent.conf"
        - "Copying /var/lib/kolla/config_files/src/etc/ovn-bgp-agent/10-neutron-ovn.conf to /etc/ovn-bgp-agent/10-neutron-ovn.conf"
