---

# Copyright 2020 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# All variables intended for modification should be placed in this file.

# All variables within this role should have a prefix of "edpm_network_config"

# This variable lets the user choose which tool will be used to configure networking on hosts
# Accepted values are:
# * os-net-config (default) -> the os-net-config tool will be used
#   - Can use either ifcfg or nmstate as internal provider based on edpm_network_config_nmstate
# * nmstate (experimental, unsupported) -> the network role from linux-system-roles/rhel-system-roles will be used
#   directly to configure networking on hosts. Refer to nmstate.io for configuration snippets.
edpm_network_config_tool: os-net-config

# Must be set to true to allow usage of nmstate as edpm_network_config_tool
edpm_network_config_tool_nmstate_override: false

# Packages needed by nmstate (via system-role)
edpm_network_config_systemrole_nmstate_dependencies:
  - NetworkManager-ovs

# seconds between retries for download tasks
edpm_network_config_download_delay: "{{ edpm_download_delay | default(60) }}"

# number of retries for download tasks
edpm_network_config_download_retries: "{{ edpm_download_retries | default(5) }}"

edpm_network_config_update: false
edpm_network_config_async_poll: 3
edpm_network_config_async_timeout: 300
edpm_network_config_bridge_name: br-ex
edpm_network_config_debug: "{{ (ansible_verbosity | int) >= 2 | bool }}"
edpm_network_config_hide_sensitive_logs: true
edpm_network_config_interface_name: nic1
edpm_network_config_manage_service: true
# Controls which provider os-net-config uses internally:
# * true (default) -> os-net-config uses nmstate provider (NetworkManager-based)
# * false -> os-net-config uses ifcfg provider (legacy network scripts)
# Note: This only applies when edpm_network_config_tool is 'os-net-config'
edpm_network_config_nmstate: true
edpm_network_config_os_net_config_mappings: {}
edpm_network_config_safe_defaults: false
edpm_network_config_template: ""
edpm_bond_interface_ovs_options: "bond_mode=active-backup"
edpm_dns_search_domains: []
edpm_network_config_nonconfigured_cleanup: true
# Control resolv.conf management by NetworkManager
# false = disable NetworkManager resolv.conf update (default)
# true = enable NetworkManager resolv.conf updat
edpm_bootstrap_network_resolvconf_update: "{{ edpm_network_config_nmstate | default(True) }}"
