---
galaxy_info:
  namespace: openstack
  author: OpenStack
  description: EDPM OpenStack Role -- edpm_telemetry_accel_exporters
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: '2.9'
  platforms:
    - name: 'EL'
      versions:
        - '9'

  galaxy_tags:
    - edpm

dependencies: []
