---
argument_specs:
  # ./roles/edpm_neutron_metadata/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_neutron_metadata role.
    options:
      edpm_neutron_metadata_images_download_delay:
        type: int
        default: 5
        description: The seconds between retries for failed download tasks
      edpm_neutron_metadata_images_download_retries:
        type: int
        default: 5
        description: The number of retries for failed download tasks
      edpm_neutron_metadata_agent_agent_report_interval:
        default: '300'
        description: ''
        type: str
      edpm_neutron_metadata_agent_image:
        default: quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:current-podified
        description: ''
        type: str
      edpm_neutron_metadata_agent_log_dir:
        default: /var/log/neutron
        description: ''
        type: str
      edpm_neutron_metadata_agent_lib_dir:
        default: "/var/lib/neutron"
        description: |
          The path to the directory containing files required by the Neutron OVN metadata
          agent, like e.g. sidecar container wrappers.
        type: str
      edpm_neutron_metadata_agent_DEFAULT_debug:
        default: 'True'
        description: ''
        type: str
      edpm_neutron_metadata_agent_DEFAULT_metadata_proxy_shared_secret:
        default: ''
        description: ''
        type: str
      edpm_neutron_metadata_agent_DEFAULT_metadata_workers:
        default: '2'
        description: ''
        type: str
      edpm_neutron_metadata_agent_DEFAULT_nova_metadata_host:
        description: 'Nova Metadata host to forward metadata requests to.'
        type: str
      edpm_neutron_metadata_agent_DEFAULT_nova_metadata_protocol:
        default: http
        description: ''
        type: str
      edpm_neutron_metadata_agent_DEFAULT_state_path:
        default: /var/lib/neutron
        description: ''
        type: str
      edpm_neutron_metadata_agent_agent_root_helper:
        default: sudo neutron-rootwrap /etc/neutron/rootwrap.conf
        description: ''
        type: str
      edpm_neutron_metadata_agent_ovn_ovn_sb_connection:
        default: ''
        description: ''
        type: str
      edpm_neutron_metadata_agent_ovn_ovsdb_probe_interval:
        default: '60000'
        description: ''
        type: str
      edpm_neutron_metadata_agent_ovs_ovsdb_connection:
        default: tcp:127.0.0.1:6640
        description: ''
        type: str
      edpm_neutron_metadata_agent_ovs_ovsdb_connection_timeout:
        default: '180'
        description: ''
        type: str
      edpm_neutron_metadata_agent_oslo_concurrency_lock_patch:
        default: $state_path/lock
        description: ''
        type: str
      edpm_neutron_metadata_agent_rootwrap_DEFAULT_daemon_timeout:
        default: '600'
        description: ''
        type: str
      edpm_neutron_metadata_agent_rootwrap_DEFAULT_exec_dirs:
        default: /sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin,/etc/neutron/kill_scripts
        description: ''
        type: str
      edpm_neutron_metadata_agent_rootwrap_DEFAULT_filters_path:
        default: /usr/share/neutron/rootwrap
        description: ''
        type: str
      edpm_neutron_metadata_agent_rootwrap_DEFAULT_rlimit_nofile:
        default: '1024'
        description: ''
        type: str
      edpm_neutron_metadata_agent_rootwrap_DEFAULT_syslog_log_facility:
        default: syslog
        description: ''
        type: str
      edpm_neutron_metadata_agent_rootwrap_DEFAULT_syslog_log_level:
        default: ERROR
        description: ''
        type: str
      edpm_neutron_metadata_agent_rootwrap_DEFAULT_use_syslog:
        default: 'False'
        description: ''
        type: str
      edpm_neutron_metadata_common_volumes:
        default:
          - /run/openvswitch:/run/openvswitch:z
          - '{{ edpm_neutron_metadata_agent_config_dir }}:/etc/neutron.conf.d:z'
          - /run/netns:/run/netns:shared
          - /var/log/containers/neutron:/var/log/neutron:z
          - /var/lib/kolla/config_files/ovn_metadata_agent.json:/var/lib/kolla/config_files/config.json:ro
          - "{{ edpm_neutron_metadata_agent_lib_dir }}:/var/lib/neutron:shared,z"
          - "{{ edpm_neutron_metadata_agent_lib_dir }}/ovn_metadata_haproxy_wrapper:/usr/local/bin/haproxy:ro"
          - "{{ edpm_neutron_metadata_agent_lib_dir }}/kill_scripts:/etc/neutron/kill_scripts:ro"
        description: ''
        elements: str
        type: list
      edpm_neutron_metadata_agent_config_dir:
        default: /var/lib/config-data/ansible-generated/neutron-ovn-metadata-agent
        description: 'The directory that contains configuration files for Neutron OVN Metadata Agent.'
        type: str
      edpm_neutron_metadata_agent_sidecar_debug:
        default: false
        description: "Enable or disable DEBUG mode in the sidecar wrappers scripts"
        type: bool
      edpm_neutron_metadata_agent_sidecar_haproxy_image_name:
        default: "{{ edpm_neutron_metadata_agent_image }}"
        description: Image used to spawn haproxy sidecar containers.
        type: str
      edpm_neutron_metadata_agent_tls_enabled:
        type: bool
        default: false
        description: >
          Enable TLS for ovnsb connection
      edpm_neutron_metadata_tls_volumes:
        type: list
        elements: str
        default:
          - /var/lib/openstack/certs/neutron_metadata_agent/default/ca.crt:/etc/pki/tls/certs/ovndbca.crt:ro,z
          - /var/lib/openstack/certs/neutron_metadata_agent/default/tls.crt:/etc/pki/tls/certs/ovndb.crt:ro,z
          - /var/lib/openstack/certs/neutron_metadata_agent/default/tls.key:/etc/pki/tls/private/ovndb.key:ro,Z
          - /var/lib/openstack/cacerts/neutron_metadata_agent/tls-ca-bundle.pem:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:ro,z
