---
edpm_accel_drivers_auto_detect: true
edpm_accel_drivers_blacklist_nouveau: true

edpm_accel_drivers_install_nvidia: false
edpm_accel_drivers_nvidia_custom_url: ""
edpm_accel_drivers_nvidia_custom_url_ssl_no_verify: false
edpm_accel_drivers_nvidia_repo_url: ""
edpm_accel_drivers_nvidia_repo_gpgkey: ""
edpm_accel_drivers_nvidia_rpm_disable_gpg_check: false
edpm_accel_drivers_nvidia_dnf_module_stream: "latest"
edpm_accel_drivers_nvidia_package_name: "nvidia-driver"
edpm_accel_drivers_nvidia_cleanup_temp_files: true

edpm_accel_drivers_nvidia_cache_dir: "/var/cache/nvidia-drivers"
edpm_accel_drivers_download_delay: "{{ edpm_download_delay | default(60) }}"
edpm_accel_drivers_download_retries: "{{ edpm_download_retries | default(5) }}"
