---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  provision: no
  parallel: true
  # default_box: 'generic/rocky9'
  default_box: 'generic/centos9s'
platforms:
- name: compute-1
  memory: 8192
  cpus: 8
  provider_options:
    cpu_mode: 'host-passthrough'
    nested: true
    machine_type: 'q35'
  groups:
    - compute
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
    prepare: ../default/prepare.yml
  inventory:
    links:
      hosts: ./inventory/hosts

verifier:
  name: ansible
scenario:
  # we disable all tests so that we dont
  # run this in ci.
  test_sequence: []
