---
argument_specs:
  # ./roles/edpm_network_config/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_network_config role.
    options:
      edpm_network_config_systemrole_nmstate_dependencies:
        type: list
        default:
          - NetworkManager-ovs
        description: Packages needed by nmstate (via system-role)
      edpm_network_config_download_delay:
        type: int
        default: 5
        description: The seconds between retries for failed download tasks
      edpm_network_config_download_retries:
        type: int
        default: 5
        description: The number of retries for failed download tasks
      edpm_network_config_tool:
        type: str
        description: >
          Which network config tool should be used. The `nmstate` will call `systemroles.network`.
        default: os-net-config
        choices:
          - os-net-config
          - nmstate
      edpm_network_config_update:
        type: bool
        description: Apply NetworkConfig or not
        default: false
      edpm_network_config_async_poll:
        type: int
        description: "How often will the edpm_os_net_config module be polled."
        default: 3
      edpm_network_config_async_timeout:
        type: int
        description: "Time before edpm_os_net_config call times out."
        default: 300
      edpm_network_config_debug:
        type: bool
        description: "Debugging output enabled"
        default: false
      edpm_network_config_hide_sensitive_logs:
        type: bool
        description: "Hide logs of potentially sensitive nature."
        default: true
      edpm_network_config_manage_service:
        type: bool
        description: "Enable the network service or not"
        default: true
      edpm_network_config_nmstate:
        type: bool
        description: "Uses nmstate and network manager for network configuration if enabled, otherwise ifcfg scripts will be used"
        default: true
      edpm_network_config_os_net_config_mappings:
        type: dict
        description: "Per node and/or per node group configuration map. Used by the edpm_os_net_config_mappings module."
        default: {}
      edpm_network_config_purge_provider:
        type: str
        description: >
          Purge the network configuration created previously using the provider specified in 'str'
          either ifcfg or nmstate. Also ensure minimum_config should be provided in your
          edpm_network_config_template variable to maintain control plane connectivity.
          This variable should be used for day2 network provider migration.
        default: ""
        choices:
          - ""
          - "ifcfg"
          - "nmstate"
      edpm_network_config_safe_defaults:
        type: bool
        description: >
          If enabled, safe defaults (DHCP for all interfaces) will be applied in
          case of failing while applying the provided net config.
        default: false
      edpm_network_config_template:
        type: str
        description: "Which settings template should be rendered."
        default: ""
      edpm_bond_interface_ovs_options:
        type: str
        description: "Binding options to be rendered in a template"
        default: "bond_mode=active-backup"
      neutron_physical_bridge_name:
        type: str
        description: "Name of the physical bridge"
        default: br-ex
      neutron_public_interface_name:
        type: str
        description: "Name of the public network interface"
        default: nic1
      edpm_network_config_nonconfigured_cleanup:
        type: bool
        description: "Cleanup network interfaces not in network config"
        default: true
      edpm_bootstrap_network_resolvconf_update:
        type: bool
        default: true
        description: |
          Control resolv.conf management by NetworkManager
          false = disable NetworkManager resolv.conf update (default)
          true = enable NetworkManager resolv.conf update
