---
argument_specs:
  # ./roles/edpm_neutron_dhcp/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_neutron_dhcp role.
    options:
      edpm_neutron_dhcp_images_download_delay:
        type: int
        default: 5
        description: The seconds between retries for failed download tasks
      edpm_neutron_dhcp_images_download_retries:
        type: int
        default: 5
        description: The number of retries for failed download tasks
      edpm_neutron_dhcp_agent_config_src:
        default: "/var/lib/openstack/configs/neutron-dhcp"
        description: |
          The path to the directory containing source of the Neutron DHCP
          agent configs.
        type: str
      edpm_neutron_dhcp_agent_config_dir:
        default: "/var/lib/config-data/ansible-generated/neutron-dhcp-agent"
        description: |
          The path to the directory containing Neutron DHCP agent config
          files.
        type: str
      edpm_neutron_dhcp_agent_lib_dir:
        default: "/var/lib/neutron"
        description: |
          The path to the directory containing files required by the Neutron DHCP
          agent, like e.g. sidecar container wrappers.
        type: str
      edpm_neutron_dhcp_image:
        default: "quay.io/podified-antelope-centos9/openstack-neutron-dhcp-agent:current-podified"
        description: Neutron DHCP agent container image.
        type: str
      edpm_neutron_dhcp_common_volumes:
        default:
          - /run/netns:/run/netns:shared
          - "{{ edpm_neutron_dhcp_agent_config_dir }}:/etc/neutron.conf.d:z"
          - /var/lib/neutron:/var/lib/neutron:shared,z
          - /var/lib/kolla/config_files/neutron_dhcp_agent.json:/var/lib/kolla/config_files/config.json:ro
          - /var/log/containers/neutron:/var/log/neutron:z
          - /run/openvswitch:/run/openvswitch:shared,z
          - "{{ edpm_neutron_dhcp_agent_lib_dir }}/dhcp_agent_haproxy_wrapper:/usr/local/bin/haproxy:ro"
          - "{{ edpm_neutron_dhcp_agent_lib_dir }}/dhcp_agent_dnsmasq_wrapper:/usr/local/bin/dnsmasq:ro"
          - "{{ edpm_neutron_dhcp_agent_lib_dir }}/kill_scripts:/etc/neutron/kill_scripts:ro"
        description: List of volumes in a mount point form.
        type: list
      edpm_neutron_dhcp_sidecar_debug:
        default: false
        description: "Enable or disable DEBUG mode in the sidecar wrappers scripts"
        type: bool
      edpm_neutron_dhcp_sidecar_haproxy_image_name:
        default: "{{ edpm_neutron_dhcp_image }}"
        description: Image used to spawn haproxy sidecar containers.
        type: str
      edpm_neutron_dhcp_sidecar_dnsmasq_image_name:
        default: "{{ edpm_neutron_dhcp_image }}"
        description: Image used to spawn dnsmasq sidecar containers.
        type: str
      edpm_neutron_dhcp_DEFAULT_debug:
        default: false
        description: "Enable or disable DEBUG mode in the Neutron DHCP agent"
        type: bool
      edpm_neutron_dhcp_DEFAULT_rpc_response_timeout:
        default: 60
        description: ''
        type: int
      edpm_neutron_dhcp_DEFAULT_transport_url:
        default: ''
        description: ''
        type: str
      edpm_neutron_dhcp_oslo_concurrency_lock_patch:
        default: '$state_path/lock'
        description: ''
        type: str
      edpm_neutron_dhcp_oslo_messaging_rabbit_heartbeat_timeout_threshold:
        default: 60
        description: ''
        type: int
      edpm_neutron_dhcp_oslo_middleware_enable_proxy_headers_parsing:
        default: 60
        description: ''
        type: int
      edpm_neutron_dhcp_rootwrap_DEFAULT_filters_path:
        default: '/etc/neutron/rootwrap.d,/usr/share/neutron/rootwrap'
      edpm_neutron_dhcp_rootwrap_DEFAULT_exec_dirs:
        default: '/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin,/etc/neutron/kill_scripts'
      edpm_neutron_dhcp_rootwrap_DEFAULT_use_syslog:
        default: false
        description: ''
        type: bool
      edpm_neutron_dhcp_rootwrap_DEFAULT_syslog_log_facility:
        default: 'syslog'
        description: ''
        type: str
      edpm_neutron_dhcp_rootwrap_DEFAULT_syslog_log_level:
        default: 'ERROR'
        description: ''
        type: str
      edpm_neutron_dhcp_rootwrap_DEFAULT_daemon_timeout:
        default: 600
        description: ''
        type: int
      edpm_neutron_dhcp_rootwrap_DEFAULT_rlimit_nofile:
        default: 1024
        description: ''
        type: int
      edpm_neutron_dhcp_agent_DEFAULT_state_path:
        default: '/var/lib/neutron'
        description: ''
        type: str
      edpm_neutron_dhcp_agent_DEFAULT_host:
        default: '{{ ansible_facts["nodename"] }}'
        description: ''
        type: str
      edpm_neutron_dhcp_agent_DEFAULT_resync_interval:
        default: 5
        description: ''
        type: int
      edpm_neutron_dhcp_agent_DEFAULT_resync_throttle:
        default: 1
        description: ''
        type: int
      edpm_neutron_dhcp_agent_DEFAULT_dhcp_driver:
        default: 'neutron.agent.linux.dhcp.Dnsmasq'
        description: ''
        type: str
      edpm_neutron_dhcp_agent_DEFAULT_enable_isolated_metadata:
        default: false
        description: ''
        type: bool
      edpm_neutron_dhcp_agent_DEFAULT_force_metadata:
        default: '/var/lib/neutron'
        description: ''
        type: str
      edpm_neutron_dhcp_agent_DEFAULT_enable_metadata_network:
        default: false
        description: ''
        type: bool
      edpm_neutron_dhcp_agent_DEFAULT_num_sync_threads:
        default: 4
        description: ''
        type: int
      edpm_neutron_dhcp_agent_DEFAULT_bulk_reload_interval:
        default: 0
        description: ''
        type: int
      edpm_neutron_dhcp_agent_DEFAULT_dnsmasq_dns_servers:
        default: ''
        description: ''
        type: str
      edpm_neutron_dhcp_agent_DEFAULT_dnsmasq_base_log_dir:
        default: ''
        description: ''
        type: str
      edpm_neutron_dhcp_agent_DEFAULT_dnsmasq_local_resolv:
        default: false
        description: ''
        type: bool
      edpm_neutron_dhcp_agent_DEFAULT_dnsmasq_lease_max:
        default: 16777216
        description: ''
        type: int
      edpm_neutron_dhcp_agent_DEFAULT_dnsmasq_enable_addr6_list:
        default: false
        description: ''
        type: bool
      edpm_neutron_dhcp_agent_DEFAULT_dhcp_broadcast_reply:
        default: false
        description: ''
        type: bool
      edpm_neutron_dhcp_agent_AGENT_root_helper:
        default: 'sudo neutron-rootwrap /etc/neutron.conf.d/01-rootwrap.conf'
        description: ''
        type: str
      edpm_neutron_dhcp_agent_AGENT_report_interval:
        default: 300
        description: ''
        type: int
