---
# Copyright 2023 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# All variables intended for modification should be placed in this file.

# All variables within this role should have a prefix of "edpm_ovn_bgp_agent"

edpm_ovn_bgp_agent_enable: true
edpm_ovn_bgp_agent_debug: true
edpm_ovn_bgp_agent_reconcile_interval: 300
edpm_ovn_bgp_agent_expose_tenant_networks: false
edpm_ovn_bgp_agent_expose_ipv6_gua_tenant_networks: false
edpm_ovn_bgp_agent_driver: ovn_bgp_driver
edpm_ovn_bgp_agent_private_key: /etc/pki/tls/private/ovn_bgp_agent.key
edpm_ovn_bgp_agent_certificate: /etc/pki/tls/certs/ovn_bgp_agent.crt
edpm_ovn_bgp_agent_ca_cert: /etc/ipa/ca.crt
edpm_ovn_bgp_agent_internal_tls_enable: false
edpm_ovn_bgp_agent_config_basedir: "/var/lib/config-data/ansible-generated/ovn-bgp-agent"
edpm_ovn_bgp_agent_bgp_as: 64999
edpm_ovn_bgp_agent_clear_vrf_routes_on_startup: false
edpm_ovn_bgp_agent_bgp_nic: bgp-nic
edpm_ovn_bgp_agent_bgp_vrf: bgp-vrf
edpm_ovn_bgp_agent_bgp_vrf_table_id: 10
edpm_ovn_bgp_agent_root_helper: "sudo ovn-bgp-agent-rootwrap /etc/ovn-bgp-agent/rootwrap.conf"
edpm_ovn_bgp_agent_root_helper_daemon: "sudo ovn-bgp-agent-rootwrap-daemon /etc/ovn-bgp-agent/rootwrap.conf"
edpm_ovn_bgp_agent_ovsdb_connection: "tcp:127.0.0.1:6640"
edpm_ovn_bgp_agent_ovs_manager: "ptcp:6640:127.0.0.1"
edpm_ovn_bgp_agent_image: "quay.io/tripleomastercentos9/openstack-ovn-bgp-agent:current-tripleo"

# optional parameters
edpm_ovn_bgp_agent_address_scopes: ''
edpm_ovn_bgp_agent_bgp_router_id: ''
edpm_ovn_bgp_agent_evpn_local_ip: ''
edpm_ovn_bgp_agent_evpn_nic: ''
edpm_ovn_bgp_agent_evpn_udp_dstport: ''  # 4789

edpm_ovn_bgp_agent_common_volumes:
  - /etc/hosts:/etc/hosts:ro
  - /etc/localtime:/etc/localtime:ro
  - /dev/log:/dev/log
  - /etc/iproute2:/etc/iproute2
  - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
  - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
  - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
  - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
  - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
  - /var/lib/kolla/config_files/ovn_bgp_agent.json:/var/lib/kolla/config_files/config.json:ro
  - /var/lib/config-data/ansible-generated/ovn-bgp-agent:/var/lib/kolla/config_files/src:ro
  - /run/frr:/run/frr:shared,z
  - /run/openvswitch:/run/openvswitch:shared,z

edpm_ovn_bgp_agent_tls_volumes:
  - /etc/pki/tls/certs/ovn_bgp_agent.crt:/etc/pki/tls/certs/ovn_bgp_agent.crt
  - /etc/pki/tls/private/ovn_bgp_agent.key:/etc/pki/tls/private/ovn_bgp_agent.key

   # we need to add the InternalTLSCAFile and do a if/then/else in case tls-e
