---

# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# All variables intended for modification should be placed in this file.

# All variables within this role should have a prefix of "edpm_sshd"
# Mapping of sshd_config values
# seconds between retries for download tasks
edpm_sshd_download_delay: "{{ edpm_download_delay | default(60) }}"

# number of retries for download tasks
edpm_sshd_download_retries: "{{ edpm_download_retries | default(5) }}"

edpm_sshd_packages:
  - openssh-server

edpm_sshd_motd_enabled: false
edpm_sshd_message_of_the_day: |
  ALERT! You are entering into a secured area!
  This service is restricted to authorized users only.
edpm_sshd_banner_enabled: false
edpm_sshd_banner_text: |
  ******************************************************************
  * This system is for the use of authorized users only. Usage of  *
  * this system may be monitored and recorded by system personnel. *
  * Anyone using this system expressly consents to such monitoring *
  * and is advised that if such monitoring reveals possible        *
  * evidence of criminal activity, system personnel may provide    *
  * the evidence from such monitoring to law enforcement officials.*
  ******************************************************************

# SSH configuration options
edpm_sshd_password_authentication: 'no'
edpm_sshd_gssapi_authentication: 'no'

edpm_sshd_server_options:
  HostKey:
    - '/etc/ssh/ssh_host_rsa_key'
    - '/etc/ssh/ssh_host_ecdsa_key'
    - '/etc/ssh/ssh_host_ed25519_key'
  SyslogFacility: 'AUTHPRIV'
  AuthorizedKeysFile: '.ssh/authorized_keys'
  ChallengeResponseAuthentication: 'no'
  GSSAPIAuthentication: "{{ edpm_sshd_gssapi_authentication }}"
  GSSAPICleanupCredentials: 'no'
  UsePAM: 'yes'
  UseDNS: 'no'
  X11Forwarding: 'yes'
  AcceptEnv:
    - 'LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES'
    - 'LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT'
    - 'LC_IDENTIFICATION LC_ALL LANGUAGE'
    - 'XMODIFIERS'
  Subsystem: 'sftp /usr/libexec/openssh/sftp-server'
  PrintMotd: 'no'

# Firewall configuration part
edpm_sshd_configure_firewall: true
edpm_sshd_allowed_ranges: ['0.0.0.0/0']
# Since we can override the port using the edpm_sshd_server_options,
# we'd rather ensure we can set the appropriate value here as well.
edpm_sshd_firewall_port: 22
