---
- name: Stop and disable old standalone container for {{ edpm_container_quadlet_service }}
  ansible.builtin.systemd_service:
    name: "{{ edpm_container_quadlet_service }}"
    state: stopped
    enabled: false
  become: true

- name: Cleanup standalone service file for {{ edpm_container_quadlet_service }}
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ edpm_container_quadlet_service }}.service"
    state: absent
  become: true
