---
# Copyright 2024 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Fail if edpm_update_system_bootc_os_container_image is not provided
  ansible.builtin.fail:
    msg: The 'edpm_update_system_bootc_os_container_image' variable is not set. Please set the value to the bootc OS image to update to.
  when: not edpm_update_system_bootc_os_container_image

- name: Switch bootc image
  ansible.builtin.shell: bootc switch "{{ edpm_update_system_bootc_os_container_image }}"
  become: true
  register: _bootc_switch_result
  changed_when: "'unchanged' not in _bootc_switch_result.stdout"

- name: Update bootc image
  ansible.builtin.shell: bootc upgrade
  become: true
  register: _bootc_upgrade_result
  changed_when: "'No changes' not in _bootc_upgrade_result.stdout"

- name: Check bootc status to see if a reboot is required
  ansible.builtin.command: bootc status --format=json
  become: true
  register: _bootc_status_result
  changed_when: false

- name: Parse bootc status output
  ansible.builtin.set_fact:
    bootc_status_json: "{{ _bootc_status_result.stdout | from_json }}"

- name: Create reboot_required directory if a deployment is staged
  become: true
  ansible.builtin.file:
    path: /var/lib/openstack/reboot_required/
    state: directory
    mode: "0755"
  when: bootc_status_json.status.staged is not none

- name: Create bootc_reboot file if a deployment is staged
  become: true
  ansible.builtin.file:
    path: /var/lib/openstack/reboot_required/bootc_reboot
    state: touch
    mode: "0600"
  when: bootc_status_json.status.staged is not none
