---
# Copyright 2024 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Update bootc image
  ansible.builtin.shell: bootc switch "{{ edpm_update_system_bootc_os_container_image }}"
  become: true
  register: bootc_switch_result
  failed_when: bootc_switch_result.rc != 0
  changed_when: false

- name: Get bootc status after switch
  ansible.builtin.shell: bootc status --format json
  become: true
  register: bootc_status
  changed_when: false

- name: Determine if update was applied
  ansible.builtin.set_fact:
    bootc_result:
      changed: "{{
        (bootc_status.stdout | from_json).status.staged is not none and
        (bootc_status.stdout | from_json).status.staged.image.imageDigest != (bootc_status.stdout | from_json).status.booted.image.imageDigest }}"

- name: Log bootc update status and reboot required information
  ansible.builtin.debug:
    msg: >-
      {% if bootc_result.changed %}
      Change/Update detected. Ready to reboot. Plan your reboot strategy before the reboot. Reboot can be disruptive and cannot be undone.
      {% else %}
      No change detected. Already running desired image. No reboot required.
      {% endif %}

- name: Create directory required by edpm-reboot role
  become: true
  ansible.builtin.file:
    path: /var/lib/openstack/reboot_required/
    state: directory
    mode: "0755"
  when:
    - bootc_result.changed

- name: Create required file to enforce a reboot
  become: true
  ansible.builtin.file:
    path: /var/lib/openstack/reboot_required/bootc_reboot
    state: touch
    mode: "0600"
  when:
    - bootc_result.changed
