---
# Copyright 2020 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Converge
  hosts: all
  gather_facts: false
  vars:
    edpm_network_config_template: |
      ---
      network_config:
        - type: interface
          name: dummy0
          use_dhcp: false
          use_dhcpv6: false
          addresses:
            - ip_netmask: 192.168.180.2
          routes:
            - ip_netmask: 192.168.181.0/24
              next_hop: 192.168.180.1
    edpm_network_config_manage_service: false
    edpm_network_config_hide_sensitive_logs: false
    edpm_network_config_nmstate: false
  pre_tasks:
    - name: Gather user fact
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - "user"

    - name: set basic user fact
      ansible.builtin.set_fact:
        ansible_user: "{{ ansible_user_id | default(lookup('env', 'USER')) }}"
      when:
        - ansible_user is undefined
  roles:
    - role: "osp.edpm.edpm_network_config"
