---
galaxy_info:
  author: OpenStack
  description: EDPM OpenStack Role -- edpm_accel_drivers
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: '2.14'
  namespace: osp
  platforms:
    - name: 'EL'
      versions:
        - '9'

  galaxy_tags:
    - edpm

dependencies: []
