---
# Copyright 2020 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Deploy services and verify state tracking
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Gather user fact
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - "user"

    - name: Set basic user fact
      ansible.builtin.set_fact:
        ansible_user: "{{ ansible_user_id | default(lookup('env', 'USER')) }}"
      when:
        - ansible_user is undefined
  tasks:
    # Deploy a service with single container
    - name: Deploy service1
      ansible.builtin.include_role:
        name: osp.edpm.edpm_container_standalone
      vars:
        edpm_container_standalone_service: service1_container
        edpm_service_name: service1
        edpm_container_standalone_container_defs:
          service1_container:
            image: quay.io/centos/centos:stream9
            net: host
            privileged: true
            restart: always
            command: sleep 3600
            environment:
              KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
        edpm_container_standalone_kolla_config_files:
          service1_container:
            command: 'sleep 3600'

    # Deploy a service with multiple containers (like telemetry)
    - name: Deploy telemetry with first container
      ansible.builtin.include_role:
        name: osp.edpm.edpm_container_standalone
      vars:
        edpm_container_standalone_service: exporter_a
        edpm_service_name: telemetry
        edpm_container_standalone_container_defs:
          exporter_a:
            image: quay.io/centos/centos:stream9
            net: host
            privileged: true
            restart: always
            command: sleep 3600
            environment:
              KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
        edpm_container_standalone_kolla_config_files:
          exporter_a:
            command: 'sleep 3600'

    - name: Deploy telemetry with second container (append)
      ansible.builtin.include_role:
        name: osp.edpm.edpm_container_standalone
      vars:
        edpm_container_standalone_service: exporter_b
        edpm_service_name: telemetry
        edpm_container_state_append: true
        edpm_container_standalone_container_defs:
          exporter_b:
            image: quay.io/centos/centos:stream9
            net: host
            privileged: true
            restart: always
            command: sleep 3600
            environment:
              KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
        edpm_container_standalone_kolla_config_files:
          exporter_b:
            command: 'sleep 3600'

    # Verify state file
    - name: Read deployed services state file
      ansible.builtin.slurp:
        src: /var/lib/edpm-config/deployed_services.yaml
      register: _state_file

    - name: Parse state data
      ansible.builtin.set_fact:
        _state_data: "{{ _state_file.content | b64decode | from_yaml }}"

    - name: Verify services are tracked
      ansible.builtin.assert:
        that:
          - "'service1' in _state_data.services"
          - "'telemetry' in _state_data.services"
          - "'service1_container' in _state_data.services.service1.containers"
          - "'exporter_a' in _state_data.services.telemetry.containers"
          - "'exporter_b' in _state_data.services.telemetry.containers"
        fail_msg: "Services should be tracked in state file"
        success_msg: "Services are properly tracked"

- name: Test service update - remove container_b and add container_c
  hosts: all
  gather_facts: false
  tasks:
    # Update telemetry: keep exporter_a, remove exporter_b, add exporter_c
    - name: Update telemetry - replace exporter_b with exporter_c
      ansible.builtin.include_role:
        name: osp.edpm.edpm_container_standalone
      vars:
        edpm_container_standalone_service: exporter_c
        edpm_service_name: telemetry
        edpm_container_standalone_container_defs:
          exporter_a:
            image: quay.io/centos/centos:stream9
            net: host
            privileged: true
            restart: always
            command: sleep 3600
            environment:
              KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
          exporter_c:
            image: quay.io/centos/centos:stream9
            net: host
            privileged: true
            restart: always
            command: sleep 3600
            environment:
              KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
        edpm_container_standalone_kolla_config_files:
          exporter_a:
            command: 'sleep 3600'
          exporter_c:
            command: 'sleep 3600'

    - name: Verify exporter_c was created
      command: podman container exists exporter_c
      changed_when: false

    - name: Read state file after update
      ansible.builtin.slurp:
        src: /var/lib/edpm-config/deployed_services.yaml
      register: _state_file_updated

    - name: Parse updated state data
      ansible.builtin.set_fact:
        _state_data_updated: "{{ _state_file_updated.content | b64decode | from_yaml }}"

    - name: Verify state file reflects the update
      ansible.builtin.assert:
        that:
          - "'telemetry' in _state_data_updated.services"
          - "'exporter_a' in _state_data_updated.services.telemetry.containers"
          - "'exporter_b' not in _state_data_updated.services.telemetry.containers"
          - "'exporter_c' in _state_data_updated.services.telemetry.containers"
        fail_msg: "State file should have exporter_a and exporter_c but not exporter_b"
        success_msg: "State file correctly reflects the updated service"

- name: Test state file removal
  hosts: all
  gather_facts: false
  tasks:
    # Remove one container from multi-container service
    - name: Remove exporter_c from telemetry
      ansible.builtin.include_role:
        name: osp.edpm.edpm_container_standalone
        tasks_from: state_file_update.yml
      vars:
        edpm_container_state_remove: true
        edpm_service_name: telemetry
        edpm_container_standalone_service: exporter_c

    - name: Read state file after container removal
      ansible.builtin.slurp:
        src: /var/lib/edpm-config/deployed_services.yaml
      register: _state_file_after_remove

    - name: Parse state data
      ansible.builtin.set_fact:
        _state_data_after_remove: "{{ _state_file_after_remove.content | b64decode | from_yaml }}"

    - name: Verify container was removed but service remains
      ansible.builtin.assert:
        that:
          - "'telemetry' in _state_data_after_remove.services"
          - "'exporter_a' in _state_data_after_remove.services.telemetry.containers"
          - "'exporter_c' not in _state_data_after_remove.services.telemetry.containers"
        fail_msg: "exporter_c should be removed but telemetry and exporter_a should remain"
        success_msg: "Container was successfully removed from service"

    # Remove last container - service should be auto-removed
    - name: Remove last container from telemetry
      ansible.builtin.include_role:
        name: osp.edpm.edpm_container_standalone
        tasks_from: state_file_update.yml
      vars:
        edpm_container_state_remove: true
        edpm_service_name: telemetry
        edpm_container_standalone_service: exporter_a

    - name: Read state file after last container removal
      ansible.builtin.slurp:
        src: /var/lib/edpm-config/deployed_services.yaml
      register: _state_file_final

    - name: Parse state data
      ansible.builtin.set_fact:
        _state_data_final: "{{ _state_file_final.content | b64decode | from_yaml }}"

    - name: Verify service was auto-removed when last container removed
      ansible.builtin.assert:
        that:
          - "'telemetry' not in _state_data_final.services"
          - "'service1' in _state_data_final.services"
        fail_msg: "telemetry should be auto-removed when last container is removed"
        success_msg: "Service was automatically removed when last container was removed"
