---
argument_specs:
  # ./roles/edpm_update/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_update role.
    description: Multiple lines description
    options:
      edpm_update_enable_packages_update:
        type: bool
        default: true
        description: Toggle to enable/disable packages updates
      edpm_update_enable_containers_update:
        type: bool
        default: true
        description: Toggle to enable/disable containers updates
      edpm_update_exclude_packages:
        type: list
        default:
          - opensvswitch
        description: List of packages to exclude from the update
