---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Create temporary file for hosts
  become: true
  ansible.builtin.tempfile:
    state: file
    suffix: tmphosts
  register: edpm_hosts_entries_tmp_hosts
  check_mode: false
  tags:
    - edpm_hosts_entries

- name: Prepare temporary /etc/hosts
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ edpm_hosts_entries_hosts_path }}"
    dest: "{{ edpm_hosts_entries_tmp_hosts.path }}"
    mode: preserve
  tags:
    - edpm_hosts_entries

- name: Render out the hosts entries
  run_once: true
  ansible.builtin.set_fact:
    edpm_hosts_entries_block: |
      {% for host in edpm_hosts_entries_overcloud_hosts_entries | default([]) +
           edpm_hosts_entries_undercloud_hosts_entries | default([]) +
           edpm_hosts_entries_extra_hosts_entries | default([]) %}
      {{ host }}
      {% endfor %}
  tags:
    - edpm_hosts_entries

- name: Prepare new /etc/hosts
  become: true
  ansible.builtin.blockinfile:
    create: true
    mode: 0644
    path: "{{ edpm_hosts_entries_tmp_hosts.path }}"
    # BOF denotes the beginning of the file.
    insertbefore: BOF
    block: "{{ edpm_hosts_entries_block }}"
    marker: "# {mark}"
    marker_begin: START_HOST_ENTRIES_FOR_STACK
    marker_end: END_HOST_ENTRIES_FOR_STACK
  register: edpm_hosts_entries_new_entries
  tags:
    - edpm_hosts_entries
  notify: Update /etc/hosts contents (if changed)

- name: Flush handlers
  meta: flush_handlers

- name: Clean up temporary hosts file
  become: true
  ansible.builtin.file:
    path: "{{ edpm_hosts_entries_tmp_hosts.path }}"
    state: absent
  when: edpm_hosts_entries_tmp_hosts.path is defined
  tags:
    - edpm_hosts_entries
