---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Converge
      block:
        - name: "Include role"
          ansible.builtin.include_role:
            name: osp.edpm.edpm_pre_adoption_validation
      rescue:
        - name: Assert that the validation passed
          ansible.builtin.fail:
            msg: "validation should pass as the old and new configs are matching"
