---

- name: Apply package updates needed for service updates
  become: true
  vars:
    _exclude_packages_always:
      - kernel
      - kernel-core
      - openvswitch
  ansible.builtin.dnf:  # noqa: package-latest
    name:
      - openstack-selinux
    state: latest
    update_cache: true
    exclude: >-
      {{
        edpm_update_services_exclude_packages
        + _exclude_packages_always
        | ansible.builtin.unique
      }}
  tags:
    - edpm_update_services
