---

- name: Install addditional packages
  ansible.builtin.dnf:
    name: "{{ edpm_kernel_extra_packages }}"
    download_only: true
  become: true
  when: edpm_kernel_extra_packages | length > 0
  register: _install_packages_result
  until: _install_packages_result.rc == 0
  retries: "{{ edpm_kernel_download_retries }}"
  delay: "{{ edpm_kernel_download_delay }}"
