---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# "edpm_kernel" will search for and load any operating system variable file

- name: Kernel tuning block
  become: true
  block:
    - name: Install additional packages
      ansible.builtin.dnf:
        name: "{{ edpm_kernel_extra_packages }}"
        state: present
      register: _install_packages_result
      when: 
      - edpm_kernel_extra_packages | length > 0
      - not ansible_local.bootc
      until: _install_packages_result is succeeded
      retries: "{{ edpm_kernel_download_retries }}"
      delay: "{{ edpm_kernel_download_delay }}"

    - name: Remove dracut-config-generic
      ansible.builtin.dnf:
        name: 'dracut-config-generic'
        state: absent

    - name: Ensure the /etc/modules-load.d/ directory exists
      ansible.builtin.file:
        path: /etc/modules-load.d
        state: directory
        mode: "0755"
        owner: root
        group: root
        setype: etc_t

    - name: Write list of modules to load at boot
      ansible.builtin.template:
        src: "edpm-modprobe.conf.j2"
        dest: "/etc/modules-load.d/99-edpm.conf"
        mode: "0644"
        owner: root
        group: root
        setype: etc_t
      register: _modprobe_result

    - name: Modules reload
      ansible.builtin.systemd:
        name: systemd-modules-load.service
        state: restarted
      when:
        - _install_packages_result.changed or _modprobe_result.changed

    - name: Render sysctl options
      ansible.builtin.template:
        src: "edpm-sysctl.conf.j2"
        dest: "/etc/sysctl.d/99-edpm.conf"
        mode: "0644"
        owner: root
        group: root
        setype: etc_t
      notify: Reload sysctl
