---
# Copyright 2023 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
- name: Prepare test_deps
  hosts: all
  roles:
    - role: ../../../../molecule/common/test_deps
      test_deps_extra_packages:
        - podman
- name: Prepare
  hosts: all
  roles:
    - role: osp.edpm.env_data
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Create config-data logging directory
      ansible.builtin.file:
        path: "{{ edpm_telemetry_logging_config_src }}"
        state: directory
        mode: "0775"

    - name: Install rsyslog
      ansible.builtin.dnf:
        name: rsyslog
        state: present

    - name: Restart rsyslog
      ansible.builtin.systemd:
        state: restarted
        name: rsyslog.service

    - name: Create ca-openshift.crt
      ansible.builtin.copy:
        dest: "{{ edpm_telemetry_logging_config_src }}/ca-openshift.crt"
        mode: "0644"
        owner: root
        group: root
        content: |
          pseudo-certificate

    - name: Create 10-telemetry.conf
      ansible.builtin.copy:
        dest: "{{ edpm_telemetry_logging_config_src }}/10-telemetry.conf"
        mode: "0644"
        owner: root
        group: root
        content: |
          action(type="omfwd" target="172.17.0.80" port="10514" protocol="tcp"
                      action.resumeRetryCount="100"
                      queue.type="linkedList" queue.size="10000"
                      StreamDriver="ossl"
                      StreamDriverMode="1"
                      StreamDriverAuthMode="x509/certvalid"
                      StreamDriver.CAFile="/etc/pki/rsyslog/ca-openshift.crt")
