- name: Converge
  hosts: all
  pre_tasks:
    - name: set basic user fact
      set_fact:
        ansible_user: "{{ lookup('env', 'USER') }}"
      when:
        - ansible_user is undefined
    - name: set basic home fact
      set_fact:
        ansible_user_dir: "{{ lookup('env', 'HOME') }}"
      when:
        - ansible_user_dir is undefined
  roles:
    - role: osp.edpm.edpm_nova
      vars:
        edpm_nova_config_src: "{{lookup('env', 'MOLECULE_PROJECT_DIRECTORY')}}/molecule/default/test-data"
        edpm_nova_tls_ca_src_dir: /tmp/pki
        edpm_nova_live_migration_tls: true
        edpm_nova_live_migration_native_tls: true
        edpm_nova_extra_bind_mounts:
          - src: /var/lib/vendor_integration
            dest: /var/lib/vendor_integration
          - src: /opt/vendor_integration_2
            dest: /opt/vendor_integration_2
            options: "shared"
        edpm_nova_nvme_cleaner_command: "/usr/bin/sleep"
        edpm_nova_nvme_cleaner_args: "infinity"
        edpm_nova_enable_nvme_cleaner: true
