---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Gather facts if they don't exist
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - "distribution"
  when: "'distribution' not in ansible_facts"
  tags:
    - always

# "{{ role_name }}" will search for and load any operating system variable file
# found within the "vars/" path. If no OS files are found the task will skip.
- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - skip: true
      files:
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_major_version'] | lower }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}-{{ ansible_facts['distribution_version'].split('.')[0] }}.yml"
        - "{{ ansible_facts['os_family'] | lower }}.yml"
  tags:
    - always

- name: Detect mirrors file
  ansible.builtin.stat:
    path: "{{ test_deps_mirrors_file_path }}"
  register: mirrors_file

- name: RHEL Block
  become: true
  when:
    - ((ansible_facts['os_family'] | lower) == 'redhat') or (mirrors_file.stat.exists | bool)
  block:
    - name: Disable ubi host subscription-manager integration
      ansible.builtin.file:
        path: /etc/rhsm-host
        state: absent

    - name: Remove ubi 9 repos
      when: ansible_facts['distribution_major_version'] is version(9, '>=')
      become: true
      ansible.builtin.file:
        path: "/etc/yum.repos.d/ubi.repo"
        state: absent

- name: Block for repo-setup
  become: true
  when:
    - (ansible_facts['os_family'] | lower) == 'redhat'
  block:
    - name: Fetch latest repo version
      ansible.builtin.uri:
        url: https://trunk.rdoproject.org/centos{{ ansible_facts['distribution_major_version'] }}/current-podified/delorean.repo
        return_content: true
      register: edpm_packages

    - name: Create default repo file
      ansible.builtin.copy:
        content: "{{ edpm_packages.content }}"
        dest: /etc/yum.repos.d/delorean.repo
        mode: 0644

- name: Install repo-setup pre-requirements
  become: true
  ansible.builtin.package:
    name:
      - git
      - python3-pip
    state: present

- name: Repo setup block
  become: true
  when:
    - (ansible_facts['os_family'] | lower) == 'redhat'
    - test_deps_setup_edpm | bool
  block:
    - name: Get repo-setup repository # noqa: latest[git]
      ansible.builtin.git:
        accept_hostkey: true
        dest: "/tmp/repo-setup"
        repo: "https://github.com/openstack-k8s-operators/repo-setup"

    - name: Install repo-setup
      ansible.builtin.shell: |
        set -eux
        cd /tmp/repo-setup
        pip install -r requirements.txt
        python3 setup.py install

    - name: Create repos
      ansible.builtin.command: /usr/local/bin/repo-setup -d ubi9 {{ test_deps_setup_stream | ternary('--stream', '--no-stream', omit) }} \
          -b master current-podified {{ test_deps_setup_ceph | ternary('ceph', '', omit) }}

    - name: Look for redhat-release rpm
      ansible.builtin.shell: |
        rpm -qe redhat-release
      register: rpm_found
      ignore_errors: true

    - name: Workaround of redhat-release binary on ubi9
      when: rpm_found.rc == 0
      ansible.builtin.shell: |
        rpm -e --nodeps redhat-release

    - name: Install edpm packages
      ansible.builtin.package:
        name: "{{ test_deps_edpm_packages }}"
        state: present
        releasever: "{{ ansible_facts['distribution_major_version'] }}"

- name: Package block
  become: true
  block:
    - name: Install selinux python libs
      ansible.builtin.package:
        name: "{{ test_deps_selinux_packages }}"
        state: present
        releasever: "{{ ansible_facts['distribution_major_version'] }}"
      when:
        - (ansible_facts['os_family'] | lower) == 'redhat'

    - name: Install python yaml libs
      ansible.builtin.package:
        name: "{{ test_deps_yaml_packages }}"
        state: present
        releasever: "{{ ansible_facts['distribution_major_version'] }}"
      when:
        - (ansible_facts['os_family'] | lower) == 'redhat'

    - name: Install extra packages
      ansible.builtin.package:
        name: "{{ test_deps_extra_packages }}"
        state: present
        releasever: "{{ ansible_facts['distribution_major_version'] }}"
      when:
        - (test_deps_extra_packages | length) > 0

- name: Bootc block
  become: true
  block:
    - name: Check for /etc/ansible/facts.d/bootc.fact
      stat:
        path: /etc/ansible/facts.d/bootc.fact
      register: bootc_fact_stat

    - name: Create /etc/ansible/facts.d
      file:
        state: directory
        path: /etc/ansible/facts.d

    - name: Create /etc/ansible/facts.d/bootc.fact
      copy:
        dest: /etc/ansible/facts.d/bootc.fact
        content: |
          #!/bin/bash
          echo "{{ test_deps_bootc_fact | lower }}"
        mode: 0755

    - name: Gather local facts
      ansible.builtin.setup:
        gather_subset:
          - "local"
