---
# Copyright 2023 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Configure network with network role from system roles [nmstate]
  when: edpm_network_config_tool == 'nmstate'
  block:
    - name: Retrieve role name [nmstate]
      ansible.builtin.set_fact:
        systemrolename:
          "{%- if ansible_facts['distribution'] == 'RedHat' -%}
            redhat.rhel
          {%- else -%}
            fedora.linux
          {%- endif -%}
          _system_roles.network"
      delegate_to: localhost
    - name: Install OVS NetworkManager plugin [nmstate]
      ansible.builtin.dnf:
        name: "{{ edpm_network_config_systemrole_nmstate_dependencies }}"
        state: present
      register: nm_ovs_status
      until: nm_ovs_status.rc == 0
      retries: "{{ edpm_network_config_download_retries }}"
      delay: "{{ edpm_network_config_download_delay }}"
    - name: Restart NetworkManager after plugin installation [nmstate]
      ansible.builtin.systemd:
        name: NetworkManager
        state: restarted
      when: nm_ovs_status.changed
    - name: Load system-roles.network tasks [nmstate]
      ansible.builtin.include_role:
        name: "{{ systemrolename }}"

- name: Load edpm_network_config tasks [os-net-config]
  ansible.builtin.include_tasks:
    file: network_config.yml
  when: edpm_network_config_tool == 'os-net-config'
