---
# Copyright 2023 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Fail when edpm_network_config_tool=nmstate unless edpm_network_config_tool_nmstate_override=true
  ansible.builtin.fail:
    msg: |
      edpm_network_config_tool=nmstate is experimental and not supported.
      Set edpm_network_config_tool_nmstate_override=true to continue anyway.
  when:
    - edpm_network_config_tool == 'nmstate'
    - not edpm_network_config_tool_nmstate_override|bool

- name: Configure network with network role from system roles [nmstate]
  when: edpm_network_config_tool == 'nmstate'
  become: true
  block:
    - name: Install OVS NetworkManager plugin [nmstate]
      ansible.builtin.dnf:
        name: "{{ edpm_network_config_systemrole_nmstate_dependencies }}"
        state: present
      register: nm_ovs_status
      until: nm_ovs_status is succeeded
      retries: "{{ edpm_network_config_download_retries }}"
      delay: "{{ edpm_network_config_download_delay }}"
    - name: Restart NetworkManager after plugin installation [nmstate]
      ansible.builtin.systemd:
        name: NetworkManager
        state: restarted
      when: nm_ovs_status.changed  # noqa: no-handler
    - name: Render network_state variable
      ansible.builtin.set_fact:
        network_state: "{{ edpm_network_config_template | from_yaml }}"
    - name: Load system-roles.network tasks [nmstate]
      ansible.builtin.include_role:
        name: "{{ lookup('ansible.builtin.env', 'EDPM_SYSTEMROLES', default='fedora.linux_system_roles') + '.network' }}"

- name: Disable auto-configuration of all interfaces by NetworkManager
  when: edpm_network_config_tool == 'os-net-config'
  become: true
  block:
    - name: Set 'no-auto-default' in /etc/NetworkManager/NetworkManager.conf
      community.general.ini_file:
        path: /etc/NetworkManager/NetworkManager.conf
        state: present
        mode: "0644"
        no_extra_spaces: true
        section: main
        option: no-auto-default
        value: "*"
        backup: true
    - name: Restart NetworkManager
      ansible.builtin.systemd:
        name: NetworkManager
        state: restarted
    - name: Load edpm_network_config tasks for os-net-config tool
      ansible.builtin.include_tasks:
        file: network_config.yml
