---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include defaults/main.yml
      ansible.builtin.include_vars: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/main.yml"

    - name: Ensure that 10-neutron-ovn.conf was copied into the container
      block:
        - name: ovn-agent config file exists
          become: true
          ansible.builtin.stat:
            path: "/var/lib/openstack/neutron-ovn-agent/10-neutron-ovn.conf"
          register: ovn_agent_config

        - name: assert that the config exists
          ansible.builtin.assert:
            that:
              - ovn_agent_config.stat.exists
            fail_msg: "ovn agent config file does not exist"

    - name: Ensure that configured root helper works
      ansible.builtin.shell: |
        podman exec ovn_agent {{ edpm_neutron_ovn_agent_agent_root_helper }} sleep 0

    - name: Slurp host specific config
      ansible.builtin.slurp:
        src: /var/lib/openstack/neutron-ovn-agent/01-neutron-ovn-agent.conf
      register: host_specific_config

    - name: Assert that host is rendered into the host specific config
      ansible.builtin.assert:
        that:
          - "'edpm-0.localdomain' in host_specific_config.content | b64decode"
