---

galaxy_info:
  role_name: edpm_chrony
  author: EDPM team
  description: EDPM OpenStack Role -- edpm_chrony
  company: Red Hat
  license: Apache 2.0
  min_ansible_version: '2.9'

  platforms:
    - name: EL
      versions:
        - '8'
        - '9'

  galaxy_tags:
    - openstack

dependencies: []
