---

- name: Download needed container images
  containers.podman.podman_image:
    name: "{{ item }}"
  loop:
    - "{{ edpm_swift_proxy_image }}"
    - "{{ edpm_swift_account_image }}"
    - "{{ edpm_swift_container_image }}"
    - "{{ edpm_swift_object_image }}"
  become: true
  register: edpm_swift_images_download
  until: edpm_swift_images_download.failed == false
  retries: "{{ edpm_swift_images_download_retries }}"
  delay: "{{ edpm_swift_images_download_delay }}"
