---
- name: Check remote connections
  ansible.builtin.import_playbook: connection.yml
- name: Configure EDPM as client of Ceph
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    # Copy files from localhost, path specified in `edpm_ceph_client_files_source`
    - name: Configure EDPM as client of Ceph
      ansible.builtin.import_role:
        name: osp.edpm.edpm_ceph_client_files
      tags:
        - edpm_ceph_client
