---
- name: Check remote connections
  ansible.builtin.import_playbook: connection.yml
- name: EDPM Download cache
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    - name: Import edpm_download_cache
      ansible.builtin.import_role:
        name: osp.edpm.edpm_download_cache
      tags:
        - edpm_download_cache
