---

- name: Deploy EDPM FRR
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  become: true
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    - name: EDPM FRR
      ansible.builtin.import_role:
        name: osp.edpm.edpm_frr
      tags:
        - edpm_frr
