---
- name: Check remote connections
  ansible.builtin.import_playbook: connection.yml
- name: EDPM Install Certs
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: free
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    - name: Install EDPM Certs
      ansible.builtin.import_role:
        name: osp.edpm.edpm_install_certs
      tags:
        - edpm_install_certs
