---

- name: Deploy EDPM Operating System Install
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    - name: Install edpm_podman
      ansible.builtin.import_role:
        name: osp.edpm.edpm_podman
        tasks_from: install.yml
      tags:
        - edpm_podman
    - name: Install edpm_sshd
      ansible.builtin.import_role:
        name: osp.edpm.edpm_sshd
        tasks_from: install.yml
      tags:
        - edpm_sshd
    # Depending on the environment we may have system roles under different name space
    # However, code executed is the same. The difference is only
    # in the mode of distribution.
    - name: Install and configure time service using timesync system role
      ansible.builtin.include_role:
        name: "{{ lookup('ansible.builtin.env', 'EDPM_SYSTEMROLES', default='fedora.linux_system_roles') + '.timesync' }}"
        apply:
          become: true
      tags:
        - dataplane_chrony
