---

- name: Deploy EDPM OVN BGP Agent Install
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: Install edpm_ovn_bgp_agent
      ansible.builtin.import_role:
        name: osp.edpm.edpm_ovn_bgp_agent
        tasks_from: install.yml
      tags:
        - edpm_ovn_bgp_agent
