---

- name: Deploy EDPM Neutron DHCP agent
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    - name: Neutron DHCP agent
      ansible.builtin.import_role:
        name: osp.edpm.edpm_neutron_dhcp
      tags:
        - edpm_neutron_dhcp
