---

- name: Deploy EDPM Neutron SR-IOV agent
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  environment: "{{ edpm_playbook_environment | default({}) }}"
  tasks:
    - name: Neutron SR-IOV agent
      ansible.builtin.import_role:
        name: osp.edpm.edpm_neutron_sriov
      tags:
        - edpm_neutron_sriov
