---
- name: Deploy EDPM Neutron OVN agent
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  become: true
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    - name: Neutron OVN agent
      ansible.builtin.import_role:
        name: osp.edpm.edpm_neutron_ovn
      tags:
        - edpm_neutron_ovn
