---

- name: Deploy Nova storage infrastructure
  hosts: all
  strategy: linear
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  environment: "{{ edpm_playbook_environment | default({}) }}"
  tasks:
    - name: Gather ansible_local facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - "local"

    - name: Deploy iSCSI daemon
      ansible.builtin.import_role:
        name: osp.edpm.edpm_iscsid
      tags:
        - edpm_iscsid
    - name: Deploy multipath daemon
      ansible.builtin.import_role:
        name: osp.edpm.edpm_multipathd
      vars:
        edpm_service_name: nova
      tags:
        - edpm_multipathd
    - name: Support NVMe-oF protocols
      ansible.builtin.import_role:
        name: osp.edpm.edpm_nvmeof
      tags:
        - edpm_nvmeof
