---

- name: Deploy Nova storage infrastructure
  hosts: all
  become: true
  strategy: linear
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    - name: Deploy iSCSI daemon
      ansible.builtin.import_role:
        name: osp.edpm.edpm_iscsid
      tags:
        - edpm_iscsid

    - name: Deploy multipath daemon
      ansible.builtin.import_role:
        name: osp.edpm.edpm_multipathd
      tags:
        - edpm_multipathd

    - name: Support NVMe-oF protocols
      ansible.builtin.import_role:
        name: osp.edpm.edpm_nvmeof
      tags:
        - edpm_nvmeof
