---

- name: Deploy EDPM Nova
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    - name: Deploy EDPM Nova
      ansible.builtin.import_role:
        name: osp.edpm.edpm_nova
      tags:
        - edpm_nova
