---

- name: Reboot nodes if reboot is required
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  tasks:
    - name: Run edpm_reboot
      ansible.builtin.import_role:
        name: osp.edpm.edpm_reboot
      tags:
        - edpm_reboot
