---

- name: Reboot nodes if reboot is required
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  gather_facts: "{{ gather_facts | default(false) }}"
  tasks:
    - name: Gather ansible_local facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - "local"
    - name: Run edpm_reboot
      ansible.builtin.import_role:
        name: osp.edpm.edpm_reboot
      tags:
        - edpm_reboot
