---
- name: Deploy EDPM Operating System Run
  hosts: all
  strategy: linear
  become: True
  tasks:
    - name: Run edpm_sshd
      import_role:
        name: osp.edpm.edpm_sshd
        tasks_from: run.yml
      tags:
        - edpm_sshd
    - name: Run edpm_chrony
      import_role:
        name: osp.edpm.edpm_chrony
        tasks_from: run.yml
      tags:
        - edpm_chrony
    - name: Run edpm_chrony (Online)
      import_role:
        name: osp.edpm.edpm_chrony
        tasks_from: online.yml
      tags:
        - edpm_chrony
    - name: Run edpm_chrony (Sync)
      import_role:
        name: osp.edpm.edpm_chrony
        tasks_from: sync.yml
      tags:
        - edpm_chrony
    - name: Run edpm_timezone
      import_role:
        name: osp.edpm.edpm_timezone
        tasks_from: run.yml
      tags:
        - edpm_timezone
    - name: Run edpm_ovn
      import_role:
        name: osp.edpm.edpm_ovn
        tasks_from: run.yml
      tags:
        - edpm_ovn
    - name: Apply nftables configuration
      import_role:
        name: osp.edpm.edpm_nftables
        tasks_from: run.yml
      when: deploy_edpm_openstack_run_firewall|default(True)|bool
      tags:
        - edpm_firewall
    - name: Run edpm_logrotate_crond
      import_role:
        name: osp.edpm.edpm_logrotate_crond
        tasks_from: run.yml
      tags:
        - edpm_logrotate_crond
    - name: Run edpm_iscsid
      import_role:
        name: osp.edpm.edpm_iscsid
        tasks_from: run.yml
      tags:
        - edpm_iscsid
