---

- name: Deploy EDPM OVN BGP Agent Run
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: Run edpm_ovn_bgp_agent
      ansible.builtin.import_role:
        name: osp.edpm.edpm_ovn_bgp_agent
        tasks_from: run.yml
      tags:
        - edpm_ovn_bgp_agent
