---

- name: Select Kernel DDP Package
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    - name: Run edpm_ddp_package
      ansible.builtin.import_role:
        name: osp.edpm.edpm_ddp_package
      tags:
        - edpm_ddp_package
