---

- name: Deploy EDPM Swift
  hosts: all
  strategy: linear
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  environment: "{{ edpm_playbook_environment | default({}) }}"
  tasks:
    - name: Deploy EDPM Swift
      ansible.builtin.import_role:
        name: osp.edpm.edpm_swift
      tags:
        - edpm_swift
