---

- name: EDPM Node validation
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    # Pings only IPv4
    - name: Import edpm_nodes_validation
      ansible.builtin.import_role:
        name: osp.edpm.edpm_nodes_validation
      tags:
        - edpm_nodes_validation
