---
argument_specs:
  # ./roles/edpm_nova/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_nova role.
    options:
      edpm_nova_image_download_delay:
        type: int
        default: 5
        description: The seconds between retries for failed download tasks
      edpm_nova_image_download_retries:
        type: int
        default: 5
        description: The number of retries for failed download tasks
      edpm_nova_config_src:
        type: str
        default: /var/lib/openstack/config
        description: |
          The path to the directory containing the nova config files
          in the ansibleEE container. This is the directory
          where all configmaps containing nova config files are mounted.
      edpm_nova_config_dest:
        type: str
        default: /var/lib/openstack/config/nova
        description: |
          The path to the directory where the nova config files
          will be rendered on the compute node.
      edpm_nova_tls_certs_enabled:
        type: bool
        default: false
        description: Boolean to specify whether TLS certs are enabled.
      edpm_nova_compute_image:
        type: str
        default: "quay.io/podified-antelope-centos9/openstack-nova-compute:current-podified"
        description: |
          The container image to use for the nova compute container.
          This image is used to create the nova compute container
          on the compute node and generaly will be set via the container
          bundle by the dataplane operator.
      edpm_nova_cpu_shared_set:
        type: str
        default: ""
        description: |
          Set to a comma-separated string or range of physical host
          CPU numbers used to.
      edpm_nova_cpu_dedicated_set:
        type: str
        default: ""
        description: |
          Set to a comma-separated string or range of host CPU cores to which
          processes for pinned instance CPUs (PCPUs) can be scheduled.
      edpm_nova_reserved_host_memory:
        type: int
        default: 4096
        description: Reserved RAM for host processes
      edpm_nova_pci_passthrough:
        type: list
        default: []
        description: |
          Set to list of SRIOV PCI passthrough dictinary with option's like
          devname, physical network and trusted etc..
