---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  provision: no
  parallel: true
  default_box: 'generic/centos9s'
platforms:
- name: edpm-multipathd
  memory: 1024
  cpus: 2
  provider_options:
    cpu_mode: 'host-passthrough'
    nested: true
    machine_type: 'q35'
  groups:
    - compute
provisioner:
  name: ansible
  playbooks:
    # Choose your scenario
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
    # prepare: ../custom_config/prepare.yml
    # converge: ../custom_config/converge.yml
    # verify: ../custom_config/verify.yml
    # prepare: ../preexisting_config/prepare.yml
    # converge: ../preexisting_config/converge.yml
    # verify: ../preexisting_config/verify.yml
verifier:
  name: ansible
scenario:
  # The vagrant scenario is for development/debug.
  # Disable all tests so they don't run in CI
  test_sequence: []
  # - destroy
  # - create
  # - prepare
  # - converge
  # - verify
