---
# Copyright 2024 Cisco Systems Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Set cacert mount if present
  block:
    - name: Determine if cacert file exists
      ansible.builtin.stat:
        path: "{{ edpm_cisco_neutron_opflex_tls_cacert_bundle_src }}"
      register: cacert_bundle_exists

    - name: Set ca_cert mount
      ansible.builtin.set_fact:
        edpm_neutron_ovn_tls_cacert_volumes:
          - "{{ edpm_cisco_neutron_opflex_tls_cacert_bundle_src }}:{{ edpm_cisco_neutron_opflex_tls_cacert_bundle_dest }}:ro,z"
      when: cacert_bundle_exists.stat.exists

- name: Ensure /usr/libexec/edpm-start-podman-container exists
  ansible.builtin.import_role:
    name: edpm_container_manage
    tasks_from: shutdown.yml

- name: Run cisco-neutron-opflex-agent container
  debugger: on_failed
  ansible.builtin.include_role:
    name: osp.edpm.edpm_container_standalone
  vars:
    edpm_container_standalone_service: ciscoaci_neutron_opflex_agent
    edpm_container_standalone_container_defs:
      ciscoaci_neutron_opflex_agent: "{{ lookup('template', 'ciscoaci_neutron_opflex_agent.yaml.j2') | from_yaml }}"
    edpm_container_standalone_kolla_config_files:
      ciscoaci_neutron_opflex_agent: "{{ lookup('template', 'kolla_config/ciscoaci_neutron_opflex_agent.yaml.j2') | from_yaml }}"