---
# Copyright 2022 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Basic config steps and basic rules
  become: true
  block:
    - name: Create snipets directory
      ansible.builtin.file:
        path: "{{ edpm_nftables_src }}"
        state: directory
        owner: root
        group: root
        mode: 0750

    - name: Push default ruleset snipet
      ansible.builtin.copy:
        dest: "{{ edpm_nftables_src }}/edpm-nftables-base.yaml"
        src: 00-base-rules.yaml

- name: IPtables compatibility layout
  become: true
  block:
    - name: Push empty ruleset
      ansible.builtin.copy:
        dest: /etc/nftables/iptables.nft
        src: iptables.nft

    - name: Load empty ruleset
      ansible.builtin.command: nft -f /etc/nftables/iptables.nft

# Get current nft rules in JSON format, with our iptables compat content.
- name: Get current nftables content
  become: true
  ansible.builtin.command: nft -j list ruleset
  register: nft_current_rules

- name: Load firewall snippets
  become: true
  register: edpm_nftables_rules_list
  edpm_nftables_from_files:
    src: "{{ edpm_nftables_src }}"

- name: nftables files generation
  become: true
  when:
    - not ansible_check_mode|bool
  block:
    # Create a dedicated file for jumps - makes easier to manage afterward.
    # That one will be loaded upon boot only.
    - name: Generate chain jumps
      ignore_errors: "{{ ansible_check_mode|bool }}"
      vars:
        current_nft: "{{ nft_current_rules }}"
        nft_is_update: false
        edpm_nftables_rules: "{{ edpm_nftables_rules_list['rules'] }}"
      ansible.builtin.template:
        dest: /etc/nftables/edpm-jumps.nft
        src: jump-chain.j2

    # Create a special "update chain jumps" file, adding just the MISSING
    # jumps in the main, default chains. This will avoid useless duplication
    # upon update/day-2 operation, since we cannot really flush INPUT and other
    # default chains.
    - name: Generate chain jumps
      ignore_errors: "{{ ansible_check_mode|bool }}"
      vars:
        current_nft: "{{ nft_current_rules }}"
        nft_is_update: true
        edpm_nftables_rules: "{{ edpm_nftables_rules_list['rules'] }}"
      ansible.builtin.template:
        dest: /etc/nftables/edpm-update-jumps.nft
        src: jump-chain.j2

    # Note: we do NOT include this one for boot, since chains are
    # already empty!
    - name: Generate nft flushes
      register: nft_flushes
      vars:
        edpm_nftables_rules: "{{ edpm_nftables_rules_list['rules'] }}"
      ansible.builtin.template:
        dest: /etc/nftables/edpm-flushes.nft
        src: flush-chain.j2

    - name: Generate nft edpm chains
      register: nft_chains
      vars:
        edpm_nftables_rules: "{{ edpm_nftables_rules_list['rules'] }}"
      ansible.builtin.template:
        dest: /etc/nftables/edpm-chains.nft
        src: chains.j2

    - name: Generate nft ruleset in static file
      register: nft_ruleset
      vars:
        edpm_nftables_rules: "{{ edpm_nftables_rules_list['rules'] }}"
      ansible.builtin.template:
        dest: /etc/nftables/edpm-rules.nft
        src: ruleset.j2

# We cannot use the "validate" parameter from the "template" module, since
# we don't load the chains before. So let's validate now, with all the things.
# Remember, the "iptables" compat layout is already loaded at this point.
- name: Validate all of the generated content before loading
  when:
    - not ansible_check_mode|bool
  ansible.builtin.shell: >-
    cat /etc/nftables/edpm-chains.nft
    /etc/nftables/edpm-flushes.nft
    /etc/nftables/edpm-rules.nft
    /etc/nftables/edpm-update-jumps.nft
    /etc/nftables/edpm-jumps.nft | nft -c -f -

# Order is important here.
# Please keep that in mind in case you want to add some new ruleset in their
# dedicated file!
- name: Ensure we load our different nft rulesets on boot
  become: true
  ansible.builtin.blockinfile:
    path: /etc/sysconfig/nftables.conf
    backup: false
    validate: nft -c -f %s
    block: |
      include "/etc/nftables/iptables.nft"
      include "/etc/nftables/edpm-chains.nft"
      include "/etc/nftables/edpm-rules.nft"
      include "/etc/nftables/edpm-jumps.nft"
